url: "https://jeandecian.github.io/info"
baseurl: "/info"
title: "Jean Decian"

collections:
  pages:
    output: true
    permalink: /:path/
  publications:
    output: true
    permalink: /publications/:path/
